baseURL = 'https://beanconqueror.com/'
languageCode = 'en-us'
title = 'Beanconqueror - As individual as your coffee'
theme = 'ananke'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 5
  [[menus.main]]
    name = 'App'
    pageRef = '/app'
    weight = 10
  [[menus.main]]
    name = 'FAQ'
    pageRef = '/app/faq'
    parent = 'App'
    weight = 1
  [[menus.main]]
    name = 'Data & Trackig'
    pageRef = '/app/data-tracking'
    parent = 'App'
    weight = 2
  [[menus.main]]
    name = 'Running Costs'
    pageRef = '/app/running-costs'
    parent = 'App'
    weight = 3
  [[menus.main]]
    name = 'Roadmap'
    pageRef = '/app/roadmap'
    parent = 'App'
    weight = 4
  [[menus.main]]
    name = 'Changelog'
    pageRef = '/app/changelog'
    parent = 'App'
    weight = 5
  [[menus.main]]
    name = 'QR-Code'
    pageRef = '/app/qrcode'
    parent = 'App'
    weight = 6
  [[menus.main]]
    name = 'Vision'
    pageRef = '/vision'
    weight = 20
  [[menus.main]]
    name = 'Team'
    pageRef = '/team'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30
  [[menus.main]]
    name = 'Github'
    pre = '<i class="fa fa-heart"></i>'
    url = 'https://github.com/graphefruit/Beanconqueror'
    weight = 50
    [menus.main.params]
      rel = 'external'
